### ISSUE TITLE
Distance not included when using Nearest

### ISSUE THREAD

**Issue by funkysi1701** [markembling/MarkEmbling.PostcodesIO#21]
I have noticed that when calling https://api.postcodes.io/postcodes/:postcode/nearest the distance is returned, however it is not returned when using Nearest(postcode) or NearestAsync(postcode)

I have forked your code to fix this, happy to create a PR if this is helpful?

**Comment by markembling** [comment]
I imagine there are a few things which are missing now - I haven't had a chance to keep this as up to date as I'd have liked. If you're happy to create a PR, by all means please do 😄

**Comment by funkysi1701** [comment]
Thanks I have create a PR for review. Not done much contributing to OS before so let me know if I have done it wrong

**Comment by markembling** [comment]
I've merged that in and pushed out a new version of the package to nuget.

The only addition I did beyond your PR was to update the tests for the nearest bits. The tests worked just fine as they were (since this was just an addition, what was there before still passed) but now they are included.

Thanks again for this.
